#!/bin/sh

# Doxygen returns 0 on warning
doxygen_output="$(doxygen 2>&1)"
if [ "$doxygen_output" != "" ]; then
  echo "Doxygen failure(s) detected:"
  echo "$doxygen_output"
  exit 1
fi

tools/coding_style.sh src/
