#/bin/sh

# Check if there is a new pugixml release
# This script must be called from the root folder
# It was written to avoid have the full pugixml as submodule / subtree

# Warning:
# - The sources are assumed to be in src/
# - New version can be unseen if they are not of the form 'v\d(.\d*)*
# - The script will not commit anything but modifies tracked files
# - The minor number of the version is not always updated (at least 1.12.1)
#   -> false positive in this case: the script will try to update

PUGIXML_URL=https://github.com/zeux/pugixml.git
PUGIXML_VERSION_PATTERN='[0-9]+(\.[0-9]*)*'
PUGIXML_LOCAL_PATH=lib/pugixml


# Get the current used release
VERSION_LINE=$(grep '^ \* pugixml parser - version ' $PUGIXML_LOCAL_PATH/pugixml.hpp)
LOCAL_VERSION=$(echo "$VERSION_LINE" | egrep -o $PUGIXML_VERSION_PATTERN)

if [ -z "$VERSION_LINE" -o -z "$LOCAL_VERSION" ]; then
  echo "Cannot identify local version. Aborting..."
  exit 1
fi


# Get the last remote version
ONLINE_VERSION=$(git ls-remote --tags "$PUGIXML_URL" \
  | egrep -o v$PUGIXML_VERSION_PATTERN \
  | sort -V \
  | tail -n 1)
if [ $? -ne 0 -o -z $ONLINE_VERSION ]; then
  echo "Cannot retrieve online version. Aborting..."
  exit 1
fi

# Stop here if the version is already actual
if [ "$LOCAL_VERSION" = "$ONLINE_VERSION" ]; then
  echo "Already using the last version $ONLINE_VERSION"
  exit 0
fi


echo "Updating: $LOCAL_VERSION -> $ONLINE_VERSION"

# Checkout the current version to update the local one
PUGIXML_TMP=/tmp/pugi_$(date +%s)
# Git is actually verbose anyway with --branch (on stderr)
git clone -q --branch "$ONLINE_VERSION" --depth 1 "$PUGIXML_URL" $PUGIXML_TMP
if [ $? -ne 0 ]; then
  echo "Cannot clone pugixml v${ONLINE_VERSION}. Aborting..."
  exit 1
fi

# Backup the current version
mv ${PUGIXML_LOCAL_PATH} ${PUGIXML_LOCAL_PATH}_old
if [ $? -ne 0 ]; then
  echo "Cannot move current pugixml"
  exit 1
fi
mkdir -p ${PUGIXML_LOCAL_PATH}

cp ${PUGIXML_TMP}/src/* ${PUGIXML_LOCAL_PATH}/
cp ${PUGIXML_TMP}/readme.txt ${PUGIXML_LOCAL_PATH}/
cp ${PUGIXML_TMP}/LICENSE.md ${PUGIXML_LOCAL_PATH}/

cmp $PUGIXML_LOCAL_PATH/LICENSE.md ${PUGIXML_LOCAL_PATH}_old/LICENSE.md
if [ $? -ne 0 ]; then
  echo
  echo "*Warning* LICENSE modification:"
fi
diff ${PUGIXML_LOCAL_PATH}/LICENSE.md ${PUGIXML_LOCAL_PATH}_old/LICENSE.md

# Update the version in the VERSION file
echo "$ONLINE_VERSION (generated by $0)" > ${PUGIXML_LOCAL_PATH}/VERSION
