#ifndef INTERFACE_HH_
# define INTERFACE_HH_

enum e_interface
{
  E_INTERFACE_IN_GAME_MENU_SELECTION_MENU_BUTTON = 0,
  E_INTERFACE_IN_GAME_MENU_SELECTION_MENU_SELECTION,

  E_INTERFACE_NB_INTERFACE
};

extern std::string g_filenames_interface[E_INTERFACE_NB_INTERFACE];


#endif /* !INTERFACE_HH_ */
