#!/bin/bash


# Generates a mapping enum value -> enum value name as a string
#
# NOTE: The given enum file must be compilable
#


if [[ $# -ne 1 ]]; then
  echo "$0: expected one argument: project root folder"
  exit 1
fi

WE_PATH=$(readlink -f "$1")
OUTPUT_DIR=/tmp/generated


# Builds a list of enum files (headers in enums/ folder)
function locate_enums_files()
{
  find $(find "${WE_PATH}/src" -name enums -type d) -name *.h*
}


# Print the guard associated with the given filename
# Note: assumes the sub-folder 'generated'
#
# $1 Header filename
#
function print_header_guard()
{
  # Expecting the header file name
  if [[ $# -ne 1 ]]; then
    echo "${FUNCNAME[0]}: Expecting 1 filename, received: $@"
    exit 1
  fi
  local filename="$1"


  # generate the guard
  local trimmed_filename=$(basename "$filename" .hh)
  local guard=GENERATED_${trimmed_filename^^}_HH_

  echo "$guard"
}



# For the prototypes header, prints
# - The Doxygen comment
# - The header guards (only ifdef / ifndef)
# - The debug namespace begin
#
# $1 Prototype filename
#
function print_prototypes_head()
{
  # Expecting the prototypes file name
  if [[ $# -ne 1 ]]; then
    echo "${FUNCNAME[0]}: Expecting 1 filename, received: $@"
    exit 1
  fi
  local filename="$1"

  # Print the doxygen comment
  echo "/**"
  echo " * \date $(date "+%B %d, %Y")"
  echo " * \author $0"
  echo " * \brief Prototypes used to print the enums values"
  echo " * \note generated by $0"
  echo " */"
  echo ""
  echo ""


  # Put the header guards (ifdef / ifndef)
  local guard=$(print_header_guard "$filename")
  echo "#ifndef $guard"
  echo "# define $guard"
  echo ""
}


# Copy the prototypes from the files generated by awk into a single header
function handle_prototypes()
{
  local prototypes="$OUTPUT_DIR"/enum_print_prototypes.hh

  # Put the doxygen header comment
  print_prototypes_head "$prototypes" > "$prototypes"

  # Copy the includes from the generated code (enum declarations)
  local gen_files=$(find "$OUTPUT_DIR" -name *.cc)
  echo '#include <string>' >> "$prototypes"
  for f in $gen_files; do
    grep -rh '# *include' "$f" | grep -v string >> "$prototypes"
  done

  # Include indentation
  sed -i s/'#include'/'# include'/g "$prototypes"
  echo -e "\n" >> "$prototypes"

  # Debug namespace
  echo -e "namespace debug {\n" >> "$prototypes"

  # Copy the prototypes from the generated code
  for f in $gen_files; do
    grep -rh std::string.*\; "$f" >> "$prototypes"
  done

  # Close the namespace
  echo -e "\n} // namespace debug\n" >> "$prototypes"

  # Close the guard
  local guard=$(print_header_guard "$prototypes")
  echo -e "\n#endif /* !$guard */" >> "$prototypes"
}



# Generate the printEnum(e_enum value); function
# $1 list of enum files
function generate_print()
{
  if [[ $# -ne 1 ]]; then
    echo "${FUNCNAME[0]}: Expecting 1 filename, received: $@"
    exit 1
  fi
  local enums_list="$1"

  for f in $enums_list; do
    local awk_gen="${OUTPUT_DIR}"/generated_$(basename "$f" .hh).cc

    # Trim comments
    g++ -x c++ -E "$f" > /tmp/$(basename "$f")

    # Invoke the awk script, generating the code
    gawk -f $(dirname "$0")/fetch_enums.awk /tmp/$(basename "$f") \
        > "$awk_gen" # --lint

    # Add the include of the enum file
    local include_enum="#include <common/enums/$(basename $f)>"
    sed -i s%'\(include.*\)'%"\1\n$include_enum"% "$awk_gen"

    # Fix the generator field in the comment
    sed -i s%'// generator:'%'// generator: '"$0"% "$awk_gen"
  done
}


# Integrate the generated code into the project folder
function integrate_generation()
{
  local generated_folder="$WE_PATH"/src/generated/enum_print
  rm -rf "$generated_folder"
  mkdir -p "$generated_folder"
  cp -a "$OUTPUT_DIR"/* "$generated_folder"

  print_generated_list "$generated_folder"
}


# Print the list of files to build (to add in src/Makefile.am)
#
# $1 folder where generated files are
#
function print_generated_list()
{
  # Expecting folder containing the generated files
  if [[ $# -ne 1 ]]; then
    echo "${FUNCNAME[0]}: Expecting 1 folder name, received: $@"
    exit 1
  fi
  local generated_folder="$1"

  echo -e "You can build the following files (add them in src/Makefile.am)\n"

  local source_list=$(find "$generated_folder" -name \*.c\*)
  for f in $source_list; do
    echo "generated/enum_print/"$(basename "$f")
  done
}


# ___________________________________ main ___________________________________ #
function main()
{
  rm -rf "$OUTPUT_DIR"
  mkdir -p "$OUTPUT_DIR"

  local enums=$(locate_enums_files)
  generate_print "$enums"
  handle_prototypes

  integrate_generation
}

main


# gen getter / print / operator ?
# return an array: {enum_name, val1, val2, ... } ?
